# Generated by Django 2.1.3 on 2019-02-06 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stationary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.IntegerField(default=50)),
                ('quantity', models.IntegerField()),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stationary.Sproduct')),
            ],
        ),
    ]
