# Generated by Django 2.1.3 on 2019-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationary', '0002_cartproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatOrder',
            fields=[
                ('StatOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(default=True)),
                ('DateOfOrder', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'StatOrderId',
            },
        ),
    ]
