# Generated by Django 2.1.3 on 2019-02-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stationary', '0004_statorderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sproduct',
            name='IsAvailable',
            field=models.BooleanField(default=True),
        ),
    ]
