# Generated by Django 2.1.3 on 2019-03-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stationary', '0005_sproduct_isavailable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'get_latest_by': 'Pid'},
        ),
    ]
