# Generated by Django 2.1.3 on 2019-02-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Roleid', models.AutoField(primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=40)),
                ('roleimg', models.ImageField(blank=True, null=True, upload_to='users_media')),
            ],
        ),
    ]
