# Generated by Django 2.1.3 on 2019-02-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_hello1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hello1',
        ),
    ]
