# Generated by Django 2.1.3 on 2019-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userprofileid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
