# Generated by Django 2.1.3 on 2019-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190214_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='userprofileid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userroleid',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Roleid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
