# Generated by Django 2.1.3 on 2019-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190217_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='enrollment',
            field=models.IntegerField(default=2, max_length=12),
            preserve_default=False,
        ),
    ]
