# Generated by Django 2.1.3 on 2019-02-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_myuser_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='enrollment',
            field=models.IntegerField(default='150670107083', max_length=12),
        ),
    ]
