# Generated by Django 2.1.3 on 2019-02-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190217_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='enrollment',
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='+910000000000', max_length=15),
        ),
    ]
