# Generated by Django 2.1.3 on 2019-02-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_myuser_userimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='userimg',
        ),
    ]
