# Generated by Django 2.1.3 on 2019-02-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_myuser_userimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='userimg',
            field=models.ImageField(blank=True, null=True, upload_to='users_media'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
