# Generated by Django 2.1.3 on 2019-03-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('queryid', models.AutoField(primary_key=True, serialize=False)),
                ('querytext', models.CharField(default='this is a query', max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('isreviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
