# Generated by Django 2.1.3 on 2019-03-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobilenumber', models.CharField(default='+910000000000', max_length=15)),
            ],
        ),
    ]
