# Generated by Django 2.1.3 on 2019-03-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='otp',
            field=models.IntegerField(default=10),
        ),
    ]
