# Generated by Django 2.1.3 on 2019-03-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20190313_0039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobile',
            options={'get_latest_by': 'mobilenumber'},
        ),
    ]
