# Generated by Django 2.1.3 on 2018-12-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookId', models.AutoField(primary_key=True, serialize=False)),
                ('BookName', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('CoverPageImg', models.ImageField(blank=True, null=True, upload_to='Stream_media')),
                ('BackPageImg', models.ImageField(blank=True, null=True, upload_to='Stream_media')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('BcId', models.AutoField(primary_key=True, serialize=False)),
                ('BcName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('StreamId', models.AutoField(primary_key=True, serialize=False)),
                ('StreamName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='BcId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stream.BookCategory'),
        ),
        migrations.AddField(
            model_name='book',
            name='StreamId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stream.Stream'),
        ),
    ]
