# Generated by Django 2.1.3 on 2018-12-12 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('BaID', models.AutoField(primary_key=True, serialize=False)),
                ('AuthorName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='IsAvailable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookauthor',
            name='BookId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stream.Book'),
        ),
    ]
