# Generated by Django 2.1.3 on 2018-12-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stream', '0002_auto_20181212_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='IsAvailable',
        ),
    ]
