# Generated by Django 2.1.3 on 2018-12-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ccategory',
            fields=[
                ('CatId', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=100)),
                ('CatImg', models.ImageField(blank=True, null=True, upload_to='Ccategory_media')),
            ],
        ),
        migrations.CreateModel(
            name='Cproduct',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False)),
                ('PName', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('CatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Ccategory')),
            ],
        ),
    ]
