# Generated by Django 2.1.3 on 2018-12-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cproduct',
            name='PImg',
            field=models.ImageField(blank=True, null=True, upload_to='Cproduct_media'),
        ),
    ]
