# Generated by Django 2.1.3 on 2018-12-07 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0002_cproduct_pimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cproduct',
            options={'get_latest_by': 'Pid'},
        ),
    ]
