# Generated by Django 2.1.3 on 2018-12-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0004_cproduct_isavailable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corders',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('DateOfOrder', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField()),
                ('CatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Ccategory')),
                ('OrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Corders')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Cproduct')),
            ],
        ),
    ]
