# Generated by Django 2.1.3 on 2018-12-17 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Canteen', '0006_auto_20181217_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCart',
            fields=[
                ('TempId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Cproduct')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
