# Generated by Django 2.1.3 on 2018-12-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0007_auto_20181217_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcart',
            name='products',
            field=models.ManyToManyField(to='Canteen.CartProduct'),
        ),
        migrations.AddField(
            model_name='tempcart',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
