# Generated by Django 2.1.3 on 2018-12-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0008_auto_20181217_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='CatId',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='OrderId',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='Pid',
        ),
        migrations.DeleteModel(
            name='Corders',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
    ]
