# Generated by Django 2.1.3 on 2018-12-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0009_auto_20181218_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcart',
            name='Pid',
        ),
        migrations.RemoveField(
            model_name='tempcart',
            name='products',
        ),
        migrations.RemoveField(
            model_name='tempcart',
            name='user',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='product',
            new_name='productid',
        ),
        migrations.DeleteModel(
            name='TempCart',
        ),
    ]
