# Generated by Django 2.1.3 on 2018-12-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0010_auto_20181218_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='productid',
            new_name='Pid',
        ),
    ]
