# Generated by Django 2.1.3 on 2018-12-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0011_auto_20181218_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='Price',
            field=models.IntegerField(default=50),
        ),
    ]
