# Generated by Django 2.1.3 on 2018-12-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0012_cartproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='aggregate',
            field=models.IntegerField(default=50),
        ),
    ]
