# Generated by Django 2.1.3 on 2018-12-19 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0014_remove_cartproduct_aggregate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatOrder',
            fields=[
                ('CatOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(default=True)),
                ('DateOfOrder', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatOrderDetails',
            fields=[
                ('CODId', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField(default=True)),
                ('quantity', models.IntegerField()),
                ('CatOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.CatOrder')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Canteen.Cproduct')),
            ],
        ),
    ]
