# Generated by Django 2.1.3 on 2019-02-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0017_auto_20190209_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mydetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=100)),
            ],
        ),
    ]
