# Generated by Django 2.1.3 on 2019-03-08 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Canteen', '0018_mydetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'get_latest_by': 'Pid'},
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
