# Generated by Django 2.1.3 on 2019-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('BookCatId', models.AutoField(primary_key=True, serialize=False)),
                ('BookCatName', models.CharField(max_length=100)),
                ('BookCategoryImg', models.ImageField(blank=True, null=True, upload_to='Library_media')),
            ],
        ),
    ]
