# Generated by Django 2.1.3 on 2019-02-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCategory',
            new_name='BookCategory1',
        ),
    ]
