# Generated by Django 2.1.3 on 2019-02-11 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0004_book1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book1',
            options={'get_latest_by': 'BookId'},
        ),
    ]
