# Generated by Django 2.1.3 on 2019-02-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0005_auto_20190211_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStock1',
            fields=[
                ('BookStockId', models.AutoField(primary_key=True, serialize=False)),
                ('BookStockSerial', models.CharField(max_length=100)),
                ('Issued', models.BooleanField(default=False)),
                ('BookId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librarian.Book1')),
            ],
        ),
    ]
