# Generated by Django 2.1.3 on 2019-02-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0006_bookstock1'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCart1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookId', models.IntegerField(blank=True, null=True)),
                ('BookName', models.CharField(default='MYBOOK', max_length=100)),
                ('BookAuthorName', models.CharField(blank=True, default=True, max_length=100)),
                ('BookSerialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('BookStockSerial', models.CharField(default=1, max_length=100)),
                ('Edition', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
