# Generated by Django 2.1.3 on 2019-02-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0007_bookcart1'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibOrderDetails1',
            fields=[
                ('LODId', models.AutoField(primary_key=True, serialize=False)),
                ('BookId', models.IntegerField(default=True)),
                ('BookSerialNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('BookStockSerial', models.CharField(default='01', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryOrder1',
            fields=[
                ('LibOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField(default=True)),
                ('DateOfOrder', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'LibOrderId',
            },
        ),
        migrations.AddField(
            model_name='liborderdetails1',
            name='LibOrderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Librarian.LibraryOrder1'),
        ),
    ]
