# Generated by Django 2.1.3 on 2019-02-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0008_auto_20190211_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='liborderdetails1',
            name='BookName',
            field=models.CharField(default='MYBOOK', max_length=100),
        ),
    ]
