# Generated by Django 2.1.3 on 2019-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0009_liborderdetails1_bookname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('ReturnId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
