# Generated by Django 2.1.3 on 2019-02-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0012_returnbook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReturnBook',
        ),
    ]
