# Generated by Django 2.1.3 on 2019-02-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0013_delete_returnbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('ReturnId', models.AutoField(primary_key=True, serialize=False)),
                ('ReturnDate', models.DateTimeField(auto_now_add=True)),
                ('DateOfOrder', models.DateTimeField(blank=True)),
                ('Fine', models.IntegerField(null=True)),
                ('BookStockSerial', models.CharField(default='01', max_length=100)),
            ],
        ),
    ]
