# Generated by Django 2.1.3 on 2019-02-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0014_returnbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnbook',
            name='Fine',
        ),
    ]
