# Generated by Django 2.1.3 on 2019-02-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0015_remove_returnbook_fine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returnbook',
            options={'get_latest_by': 'ReturnId'},
        ),
    ]
