# Generated by Django 2.1.3 on 2019-02-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Librarian', '0018_fineamount1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fineamount1',
            name='FineAmount',
            field=models.IntegerField(default=0),
        ),
    ]
