# Generated by Django 2.1.3 on 2019-02-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='id',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userrole',
            name='UserRoleId',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'student'), ('CANTEEN_OWNER', 'canteen_owner'), ('STATIONARY_OWNER', 'stationary_owner'), ('LIBRARIAN', 'librarian')], max_length=8),
        ),
    ]
