# Generated by Django 2.1.3 on 2019-02-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0005_auto_20190213_2329'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole1',
            fields=[
                ('UserRoleId', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
