# Generated by Django 2.1.3 on 2019-02-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0006_userrole1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole1',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='UserRoleId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
