# Generated by Django 2.1.3 on 2019-02-13 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_auto_20190213_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
