# Generated by Django 2.1.3 on 2019-02-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_delete_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Roleid', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=30)),
            ],
        ),
    ]
