# Generated by Django 2.1.3 on 2019-02-14 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
