# Generated by Django 2.1.3 on 2019-02-14 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0011_hello'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
