# Generated by Django 2.1.3 on 2019-03-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='docid',
        ),
        migrations.AlterField(
            model_name='documents',
            name='enroll',
            field=models.IntegerField(default=151260107099, primary_key=True, serialize=False, unique=True),
        ),
    ]
